baseURL = "https://bluenick.org/"
languageCode = "en-us"
title = "Blue Nick"
theme = "hextra"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = false
hasCJKLanguage = true

enableInlineShortcodes = true

displayUpdatedDate = true
dateFormat = "January 2, 2006"

[Params.comments]
    enable = true
    type = "giscus"
    [Params.comments.giscus]
        repo = "CodeClimberNT/bluenick-comment"
        repoId = "R_kgDONZxuTQ"
        category = "General"
        categoryId = "DIC_kwDONZxuTc4Ck-Fo"
        mapping = "pathname"
        strict = "0"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top"
        lang = "en"

[Params.navbar]
    displayTitle = false
    displayLogo = true
    [Params.navbar.logo]
        path = "favicon.svg"
        dark = "favicon.svg"
        link = "/"
        width = "32px"
        height = "32px"

        # Seems to be broken
        # [Params.editUrl]
        #     enable = true
        #     base = "https://github.com/CodeClimberNT/HowTo/edit/main/content/docs"

[Params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = false
    width = "normal"

[Params.theme]
    default = "system"
    displayToggle = true

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    noClasses = false


[[menu.main]]
    name = "Home"
    weight = 1
    pageRef = "/"

[[menu.main]]
    name = "Wiki"
    weight = 2
    pageRef = "/wiki"

[[menu.main]]
    name = "Blog"
    weight = 3
    pageRef = "/blog/"

[[menu.main]]
    name = "Projects"
    weight = 4
    pageRef = "/projects/"

[[menu.main]]
    name = "Search"
    weight = 5
    params = { type = "search" }

[[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/CodeClimberNT"
    params = { icon = "github" }

[services.googleAnalytics]
    ID = "G-DSWRWCNZ6C"
